2018-01-15 10:29:39,780 - LogUtils.py[line:112] - INFO: postgresql connect host .....   121.42.36.138
2018-01-15 10:29:40,101 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-15 10:30:09,873 - LogUtils.py[line:112] - INFO: .......httpClient exception error  : [Errno 111] Connection refused
2018-01-15 10:30:45,852 - LogUtils.py[line:112] - INFO: postgresql connect host .....   121.42.36.138
2018-01-15 10:30:46,109 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-15 10:30:46,127 - LogUtils.py[line:112] - INFO: .......httpClient error status : 400
2018-01-15 10:31:36,258 - LogUtils.py[line:112] - INFO: postgresql connect host .....   121.42.36.138
2018-01-15 10:31:36,519 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-15 10:31:49,303 - LogUtils.py[line:112] - INFO: .......httpClient error status : 400
2018-01-15 10:37:04,542 - LogUtils.py[line:112] - INFO: postgresql connect host .....   121.42.36.138
2018-01-15 10:37:04,775 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-15 10:37:04,794 - LogUtils.py[line:112] - INFO: .......httpClient error status : 400
2018-01-15 10:37:33,682 - LogUtils.py[line:112] - INFO: postgresql connect host .....   121.42.36.138
2018-01-15 10:37:33,939 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-15 10:37:33,959 - LogUtils.py[line:112] - INFO: .......httpClient error status : 400
2018-01-15 10:38:24,028 - LogUtils.py[line:112] - INFO: postgresql connect host .....   121.42.36.138
2018-01-15 10:38:24,294 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-15 10:38:24,311 - LogUtils.py[line:112] - INFO: .......httpClient error status : 400
2018-01-15 10:46:51,868 - LogUtils.py[line:112] - INFO: postgresql connect host .....   121.42.36.138
2018-01-15 10:46:52,132 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-15 10:46:52,152 - LogUtils.py[line:112] - INFO: .......httpClient error status : 400
2018-01-15 10:47:58,548 - LogUtils.py[line:112] - INFO: postgresql connect host .....   121.42.36.138
2018-01-15 10:47:58,805 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-15 10:47:58,824 - LogUtils.py[line:112] - INFO: .......httpClient error status : 400
2018-01-15 10:48:19,309 - LogUtils.py[line:112] - INFO: postgresql connect host .....   121.42.36.138
2018-01-15 10:48:19,604 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-15 10:48:19,931 - LogUtils.py[line:112] - INFO: [sql__get_one]....select * from fs_customer where number = '15900282168' and user_id = 8
2018-01-15 10:48:19,932 - LogUtils.py[line:112] - INFO: postgresql connect host .....   121.42.36.138
2018-01-15 10:48:19,977 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
