2018-01-04 19:39:45,044 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:39:45,284 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:40:30,570 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:40:30,848 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:41:09,407 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:41:09,462 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:41:11,613 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:41:11,668 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:41:28,260 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:41:28,297 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 19:41:59,304 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:41:59,549 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:41:59,597 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:41:59,643 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:41:59,644 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:41:59,690 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:41:59,691 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:41:59,721 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 19:43:05,188 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:43:05,426 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:43:05,477 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:43:05,524 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:43:05,524 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:43:05,569 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:43:05,569 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:43:05,615 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:44:06,698 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:44:06,941 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:44:06,987 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:44:07,035 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:44:07,037 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:44:07,089 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:44:07,091 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:44:07,137 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:47:15,188 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:47:15,452 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:47:15,499 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:47:15,543 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:47:15,544 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:47:15,598 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:48:00,463 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:48:00,762 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:48:00,804 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:48:00,873 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:48:00,873 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:48:00,925 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:48:15,186 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:48:15,424 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:48:15,465 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:48:15,514 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:48:15,515 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:48:15,558 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:48:22,936 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:48:23,173 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:48:23,213 - LogUtils.py[line:112] - INFO: .......httpClient exception error  : 'unicode' object has no attribute 'eecode'
2018-01-04 19:49:12,430 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:49:12,672 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:49:12,716 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:49:12,763 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:49:12,763 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:49:12,810 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:50:47,212 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:50:47,489 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:50:47,534 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:50:47,599 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:50:47,599 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:50:47,645 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:50:57,212 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:50:57,507 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:50:57,548 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:50:57,594 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:50:57,595 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:50:57,661 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:51:35,924 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:51:36,285 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:51:36,329 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:51:36,394 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:51:36,394 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:51:36,469 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:52:36,395 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:52:36,679 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:52:36,725 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:52:36,794 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:52:36,794 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:52:36,840 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:52:36,840 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:52:36,886 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 19:53:16,007 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:53:16,252 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:53:16,294 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:53:16,354 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:53:16,355 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:53:16,401 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:53:16,402 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:53:16,433 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 19:55:34,003 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:55:34,309 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:55:34,352 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:55:34,398 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:55:34,398 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:55:34,465 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:55:34,465 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:55:34,496 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 19:56:39,367 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:56:39,600 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:56:39,647 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:56:39,691 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:56:39,692 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:56:39,737 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:56:39,737 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:56:39,765 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 19:57:40,345 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:57:40,576 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:57:40,621 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:57:40,667 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:57:40,668 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:57:40,714 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:57:40,715 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:57:40,743 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 19:57:59,919 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:58:00,172 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:58:00,214 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:58:00,267 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:58:00,267 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:58:00,313 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 19:58:00,313 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 19:58:00,366 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:02:31,497 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:02:31,732 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:02:31,776 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:02:31,822 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:02:31,823 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:02:31,870 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:02:31,870 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:02:31,915 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:02:57,894 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:02:58,143 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:02:58,186 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:02:58,233 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:02:58,234 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:02:58,281 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:02:58,281 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:02:58,327 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:03:15,276 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:03:15,523 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:03:15,568 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:03:15,616 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:03:15,616 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:03:15,664 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:03:15,664 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:03:15,697 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 20:03:26,078 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:03:26,334 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:03:26,377 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:03:26,423 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:03:26,424 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:03:26,476 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:03:26,476 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:03:26,506 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 20:06:54,331 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:06:54,592 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:06:54,636 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:06:54,694 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:06:54,695 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:06:54,742 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:06:54,742 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:06:54,779 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 20:07:25,579 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:07:25,834 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:07:25,880 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:07:25,925 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:07:25,925 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:07:25,977 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:08:38,441 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:08:38,757 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:08:38,805 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:08:38,854 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:08:38,854 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:08:38,926 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:08:49,724 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:08:49,998 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:08:50,042 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:08:50,109 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:08:50,109 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:08:50,153 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:08:50,154 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:08:50,196 - LogUtils.py[line:120] - ERROR: runsql exception error syntax error at or near "["
LINE 1:  update fs_customer set label = [u'\u5173\u6ce8\u533b\u7597'...
                                        ^
 
2018-01-04 20:10:55,746 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:10:56,004 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:10:56,057 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:10:56,103 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:10:56,103 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:10:56,155 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:11:01,418 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:11:01,652 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:11:28,965 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:11:29,194 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:13:37,201 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:13:37,516 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:13:51,868 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:13:52,165 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:14:33,941 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:14:34,184 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:20:20,306 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:20:20,558 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:20:34,515 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:20:34,851 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:20:56,556 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:20:56,790 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:21:19,769 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:21:20,002 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:26:05,268 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:26:05,517 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:36:17,418 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:36:17,717 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:36:48,466 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:36:48,840 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:37:27,417 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:37:27,733 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:38:12,301 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:38:12,593 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:38:12,637 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:38:12,686 - LogUtils.py[line:120] - ERROR: runsql exception error malformed array literal: "{关注医疗,关注教育,}"
LINE 1:  update fs_customer set label = '{关注医疗,关注教育,}' where...
                                        ^
DETAIL:  Unexpected "}" character.
 
2018-01-04 20:38:34,594 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:38:34,956 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:38:34,999 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:38:35,045 - LogUtils.py[line:120] - ERROR: runsql exception error malformed array literal: "{关注医疗,关注教育,}"
LINE 1:  update fs_customer set label = '{关注医疗,关注教育,}' where...
                                        ^
DETAIL:  Unexpected "}" character.
 
2018-01-04 20:40:11,405 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:40:11,652 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:40:11,701 - LogUtils.py[line:112] - INFO: .......httpClient exception error  : 'unicode' object has no attribute 'Substring'
2018-01-04 20:41:04,699 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:41:04,955 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:41:05,002 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:41:05,052 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:41:53,705 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:41:54,016 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:41:54,059 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:41:54,108 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:41:54,109 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:41:54,176 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
2018-01-04 20:41:54,176 - LogUtils.py[line:112] - INFO: postgresql connect host .....   118.190.166.165
2018-01-04 20:41:54,224 - LogUtils.py[line:112] - INFO: postgresql connect.....closed!!!
